In [19]:
import pandas as pd
import ast

from collections import Counter, defaultdict
import math
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [3]:
train_df = pd.read_csv("train_df.csv")
test_df = pd.read_csv("test_df.csv")

In [4]:
train_df

                                                   tokens     category_10
0       ['united', 'states', 'high', 'school', 'gradua...        POLITICS
1       ['a', 'guide', 'to', 'unscrambling', 'trumps',...        POLITICS
2       ['watching', 'conan', 'sell', 'cheese', 'on', ...           OTHER
3       ['muggle', 'dads', 'homemade', 'diagon', 'alle...           OTHER
4       ['pandemic', 'products', 'that', 'definitely',...  STYLE & BEAUTY
...                                                   ...             ...
167616                          ['friendships', 'matter']           OTHER
167617  ['las', 'vegas', 'launches', 'gay', 'travel', ...    QUEER VOICES
167618  ['culture', 'contrasts', 'norways', 'support',...           OTHER
167619  ['daily', 'meditation', 'i', 'hear', 'america'...           OTHER
167620                ['escaping', 'from', 'the', 'dark']        POLITICS

[167621 rows x 2 columns]

In [5]:
train_df["tokens"] = train_df["tokens"].apply(ast.literal_eval)
test_df["tokens"] = test_df["tokens"].apply(ast.literal_eval)

In [6]:
train_df

                                                   tokens     category_10
0       [united, states, high, school, graduation, rat...        POLITICS
1       [a, guide, to, unscrambling, trumps, bonkers, ...        POLITICS
2       [watching, conan, sell, cheese, on, a, mexican...           OTHER
3       [muggle, dads, homemade, diagon, alley, will, ...           OTHER
4       [pandemic, products, that, definitely, belong,...  STYLE & BEAUTY
...                                                   ...             ...
167616                              [friendships, matter]           OTHER
167617  [las, vegas, launches, gay, travel, campaign, ...    QUEER VOICES
167618  [culture, contrasts, norways, support, of, wor...           OTHER
167619     [daily, meditation, i, hear, america, singing]           OTHER
167620                        [escaping, from, the, dark]        POLITICS

[167621 rows x 2 columns]

In [7]:
t = train_df.iloc[0]["tokens"]
print(t)
print(type(t))
print(type(t[0]))

['united', 'states', 'high', 'school', 'graduation', 'rate', 'reaches', 'a', 'record', 'high']
<class 'list'>
<class 'str'>

In [12]:
unigram_models = {}

categories = train_df["category_10"].unique()

for category in categories:
    cat_tokens = train_df[train_df["category_10"] == category]["tokens"]
    print(cat_tokens,'\n\n')
    all_tokens = [token for tokens in cat_tokens for token in tokens]
    print(all_tokens[:10],'\n\n')
    
    word_counts = Counter(all_tokens)
    total_tokens = sum(word_counts.values())
    vocab = set(word_counts.keys())
    
    unigram_models[category] = {
        "word_counts": word_counts,
        "total_tokens": total_tokens,
        "vocab": vocab,
        "vocab_size": len(vocab)
    }
    print(f"unigram_models{category} ,{unigram_models[category]}")

0         [united, states, high, school, graduation, rat...
1         [a, guide, to, unscrambling, trumps, bonkers, ...
12        [gop, lawmakers, to, trump, we, can, still, wo...
14        [elizabeth, warren, americans, should, keep, d...
15        [vulnerable, gop, senator, now, says, hes, wil...
                                ...
167601    [former, intel, officials, defend, john, brenn...
167606    [trump, scorns, biden, for, the, way, he, wear...
167610    [one, quote, from, abraham, lincoln, might, ju...
167614    [kentucky, neighbor, expected, to, plead, guil...
167620                          [escaping, from, the, dark]
Name: tokens, Length: 28481, dtype: object


['united', 'states', 'high', 'school', 'graduation', 'rate', 'reaches', 'a', 'record', 'high']



In [13]:
unigram_models["POLITICS"]["word_counts"].most_common(10)

[('to', 8464),
 ('the', 7738),
 ('trump', 5918),
 ('of', 4419),
 ('in', 4177),
 ('for', 3936),
 ('a', 3837),
 ('<', 3401),
 ('NUM', 3401),
 ('>', 3401)]

In [22]:
unigram_models

{'POLITICS': {'word_counts': Counter({'to': 8464,
           'the': 7738,
           'trump': 5918,
           'of': 4419,
           'in': 4177,
           'for': 3936,
           'a': 3837,
           '<': 3401,
           'NUM': 3401,
           '>': 3401,
           'on': 3284,
           'is': 2583,
           'donald': 2502,
           'and': 2371,
           'trumps': 1872,
           'with': 1651,
           'gop': 1449,
           'clinton': 1239,
           'about': 1223,
           'says': 1182,
           'new': 1092,
           'his': 1091,
           'obama': 1061,
           'are': 1056,
           'house': 1053,
           'at': 1038,
           'from': 1036,
           'hillary': 1019,
           'as': 992,
           'not': 991,
           'us': 979,
           'over': 911,
           'be': 894,
           'after': 892,
           'it': 871,
           'what': 816,
           'will': 804,
           'that': 792,
           'white': 764,
           'how': 742,
           'he': 731,
           'republicans': 702,
           'court': 698,
           'democrats': 684,
           'this': 679,
           'senate': 676,
           'you': 663,
           'sanders': 655,
           'bill': 655,
           'by': 642,
           'out': 614,
           'up': 608,
           'president': 592,
           'why': 590,
           'has': 579,
           'its': 578,
           'bernie': 572,
           'have': 569,
           'more': 560,
           'election': 559,
           'who': 534,
           'campaign': 529,
           'but': 513,
           'against': 505,
           'could': 503,
           'supreme': 501,
           'health': 500,
           'no': 497,
           'an': 496,
           'state': 477,
           'was': 475,
           'republican': 475,
           'we': 467,
           'just': 449,
           'care': 448,
           'people': 445,
           'email': 444,
           'congress': 419,
           'should': 412,
           'if': 411,
           'democratic': 411,
           'can': 403,
           'obamacare': 397,
           'americans': 393,
           'first': 388,
           'all': 376,
           'morning': 373,
           'paul': 372,
           'report': 372,
           'john': 371,
           'calls': 371,
           'huffpost': 369,
           'tax': 368,
           'vote': 367,
           'one': 364,
           'debate': 362,
           'now': 359,
           'wont': 359,
           'back': 357,
           'gun': 356,
           'their': 352,
           'get': 351,
           'plan': 351,
           'biden': 351,
           'climate': 350,
           'know': 347,
           'say': 346,
           'war': 346,
           'dont': 342,
           'would': 339,
           'ban': 332,
           'than': 330,
           'may': 329,
           'still': 328,
           'big': 321,
           'down': 316,
           'wants': 315,
           'i': 315,
           'presidential': 315,
           'law': 311,
           'cruz': 308,
           'need': 308,
           'america': 308,
           'heres': 306,
           'rights': 301,
           'her': 301,
           'voters': 300,
           'day': 299,
           'ted': 298,
           'change': 297,
           'news': 296,
           'most': 294,
           'him': 294,
           'race': 293,
           'police': 290,
           'like': 288,
           'fight': 287,
           'time': 286,
           'federal': 285,
           'russia': 284,
           'states': 282,
           'deal': 279,
           'into': 279,
           'joe': 273,
           'american': 270,
           'our': 270,
           'they': 269,
           'do': 268,
           'want': 267,
           'some': 264,
           'top': 263,
           'obamas': 263,
           'make': 260,
           'justice': 256,
           'former': 256,
           'immigration': 253,
           'women': 253,
           'party': 251,
           'doesnt': 249,
           'judge': 248,
           'shooting': 246,
           'support': 239,
           'black': 239,
           'national': 238,
           'twitter': 237,
           'really': 237,
           'off': 235,
           'texas': 235,
           'security': 234,
           'stop': 234,
           'bush': 234,
           'senator': 232,
           'ryan': 229,
           'cant': 229,
           'huffpollster': 228,
           'voter': 227,
           'or': 227,
           'administration': 224,
           'your': 220,
           'governor': 220,
           'hes': 218,
           'mike': 218,
           'rubio': 217,
           'so': 217,
           'north': 215,
           'help': 212,
           'rise': 210,
           'years': 208,
           'right': 208,
           'even': 207,
           'fbi': 206,
           'again': 205,
           'death': 205,
           'candidate': 204,
           'speech': 203,
           'attack': 202,
           'government': 202,
           'primary': 202,
           'call': 200,
           'take': 198,
           'run': 198,
           'california': 197,
           'when': 194,
           'voting': 193,
           'hill': 189,
           'policy': 187,
           'win': 187,
           'warren': 186,
           'another': 185,
           'marco': 185,
           'claims': 185,
           'political': 184,
           'year': 184,
           'violence': 182,
           'wall': 182,
           'scott': 181,
           'think': 181,
           'isnt': 181,
           'crisis': 180,
           'probe': 180,
           'secretary': 180,
           'repeal': 179,
           'gets': 179,
           'candidates': 178,
           'lawmakers': 177,
           'money': 177,
           'congressman': 177,
           'school': 176,
           'elizabeth': 176,
           'before': 176,
           'york': 175,
           'group': 175,
           'million': 174,
           'way': 174,
           'rep': 172,
           'jeb': 171,
           'abortion': 170,
           'end': 170,
           'being': 169,
           'them': 168,
           'reform': 168,
           'go': 167,
           'good': 166,
           'clintons': 165,
           'world': 164,
           'chief': 163,
           'man': 163,
           'my': 163,
           'case': 162,
           'sexual': 162,
           'iran': 161,
           'wins': 161,
           'show': 161,
           'next': 160,
           'watch': 160,
           'public': 159,
           'pick': 158,
           'carolina': 158,
           'chris': 158,
           'didnt': 157,
           'department': 157,
           'under': 157,
           'during': 155,
           'florida': 154,
           'media': 153,
           'washington': 152,
           'planned': 151,
           'shows': 151,
           'senators': 150,
           'politics': 150,
           'were': 149,
           'supporters': 149,
           'did': 148,
           'week': 148,
           'own': 148,
           'iowa': 148,
           'military': 148,
           'rules': 148,
           'attacks': 147,
           'too': 147,
           'pence': 146,
           'office': 146,
           'marijuana': 145,
           'muslim': 144,
           'jeff': 144,
           'sessions': 144,
           'history': 143,
           'rally': 143,
           'general': 142,
           'comey': 141,
           'because': 141,
           'michael': 140,
           'pay': 139,
           'tells': 138,
           'face': 136,
           'convention': 136,
           'talking': 135,
           'real': 135,
           'got': 135,
           'students': 134,
           'isis': 134,
           'she': 134,
           'latest': 134,
           'slams': 134,
           'been': 132,
           'only': 132,
           'epa': 132,
           'does': 132,
           'russian': 131,
           'legal': 131,
           'push': 131,
           'these': 131,
           'nominee': 130,
           'roundup': 130,
           'getting': 130,
           'order': 129,
           'mayor': 129,
           'other': 129,
           'democrat': 129,
           'parenthood': 129,
           'poll': 129,
           'border': 129,
           'fraud': 128,
           'must': 128,
           'reportedly': 128,
           'polls': 128,
           'fox': 127,
           'keep': 127,
           'travel': 127,
           'control': 127,
           'ad': 127,
           'union': 126,
           'steve': 126,
           'congressional': 126,
           'problem': 125,
           'going': 124,
           'mcconnell': 123,
           'ben': 122,
           'official': 122,
           'very': 122,
           'key': 122,
           'budget': 122,
           'takes': 121,
           'kids': 121,
           'makes': 121,
           'last': 121,
           'bad': 120,
           'running': 119,
           'protesters': 119,
           'leaders': 119,
           'actually': 119,
           'days': 118,
           'workers': 117,
           'secret': 117,
           'racist': 117,
           'civil': 117,
           'moore': 117,
           'christie': 117,
           'lawyer': 116,
           'roy': 116,
           'behind': 116,
           'give': 116,
           'work': 115,
           'comments': 115,
           'much': 114,
           'water': 114,
           'social': 114,
           'guns': 114,
           'americas': 114,
           'james': 113,
           'talk': 112,
           'wrong': 112,
           'never': 112,
           'had': 112,
           'lead': 112,
           'drug': 112,
           'trade': 111,
           'thinks': 111,
           'laws': 111,
           'threat': 111,
           'amid': 111,
           'officials': 111,
           'gov': 111,
           'open': 111,
           'there': 111,
           'investigation': 110,
           'attorney': 110,
           'lives': 110,
           'meeting': 110,
           'committee': 110,
           'sen': 109,
           'super': 109,
           'nuclear': 109,
           'spending': 109,
           'defends': 108,
           'yet': 108,
           'said': 108,
           'ferguson': 108,
           'south': 108,
           'georgia': 108,
           'country': 108,
           'response': 107,
           'trying': 107,
           'virginia': 107,
           'while': 107,
           'me': 107,
           'city': 107,
           'foreign': 107,
           'special': 107,
           'look': 107,
           'carson': 106,
           'march': 106,
           'power': 106,
           'mueller': 106,
           'act': 106,
           'george': 106,
           'family': 106,
           'conservative': 105,
           'director': 105,
           'lawmaker': 104,
           'made': 104,
           'here': 104,
           'mccain': 104,
           'see': 103,
           'warns': 103,
           'immigrants': 103,
           'tweet': 103,
           'dnc': 103,
           'marriage': 103,
           'use': 102,
           'gops': 102,
           'team': 102,
           'plans': 102,
           'points': 102,
           'shutdown': 101,
           'protest': 101,
           'job': 101,
           'business': 101,
           'cut': 101,
           'where': 100,
           'major': 100,
           'questions': 100,
           'woman': 100,
           'letter': 99,
           'assault': 99,
           'rick': 99,
           'video': 99,
           'without': 99,
           'might': 98,
           'capitol': 98,
           'tweets': 98,
           'mitch': 98,
           'cuts': 97,
           'arent': 97,
           'covid': 97,
           'away': 97,
           'gay': 97,
           'despite': 96,
           'claim': 96,
           'block': 96,
           'thing': 96,
           'free': 96,
           'two': 96,
           'progressive': 95,
           'better': 95,
           'save': 95,
           'finally': 95,
           'goes': 94,
           'groups': 94,
           'college': 94,
           'pelosi': 94,
           'many': 93,
           'ahead': 93,
           'victory': 93,
           'flint': 93,
           'defense': 93,
           'best': 92,
           'theres': 92,
           'street': 92,
           'hate': 91,
           'sunday': 91,
           'mass': 91,
           'iraq': 91,
           'conservatives': 91,
           'live': 91,
           'decision': 90,
           'press': 90,
           'action': 90,
           'times': 90,
           'meet': 90,
           'votes': 90,
           'friday': 90,
           'doj': 89,
           'fake': 89,
           'endorses': 89,
           'leader': 89,
           'dems': 89,
           'future': 89,
           'let': 89,
           'high': 88,
           'prison': 88,
           'syria': 88,
           'matter': 88,
           'victims': 88,
           'ready': 88,
           'ever': 88,
           'emails': 88,
           'activists': 88,
           'access': 88,
           'rand': 87,
           'part': 87,
           'cia': 87,
           'fire': 87,
           'alabama': 86,
           'im': 86,
           'korea': 86,
           'barack': 86,
           'suggests': 86,
           'gives': 85,
           'leave': 85,
           'force': 85,
           'schools': 85,
           'ivanka': 85,
           'ohio': 85,
           'story': 85,
           'tell': 84,
           'set': 84,
           'asks': 84,
           'announces': 84,
           'presidency': 84,
           'nomination': 84,
           'great': 83,
           'democracy': 83,
           'move': 83,
           'making': 83,
           'adviser': 82,
           'second': 82,
           'funding': 82,
           'already': 82,
           'stand': 82,
           'love': 82,
           'hits': 81,
           'things': 81,
           'put': 81,
           'executive': 81,
           'putin': 81,
           'read': 81,
           'refugees': 81,
           'kasich': 81,
           'release': 81,
           'finds': 81,
           'scandal': 81,
           'child': 81,
           'hell': 81,
           'record': 80,
           'dead': 80,
           'whats': 80,
           'dc': 80,
           'service': 80,
           'life': 80,
           'idea': 80,
           'harassment': 80,
           'system': 80,
           'lawsuit': 80,
           'hampshire': 80,
           'nancy': 80,
           'theyre': 80,
           'transgender': 80,
           'results': 79,
           'education': 79,
           'aide': 79,
           'since': 79,
           'rnc': 79,
           'immigrant': 79,
           'whether': 79,
           'faces': 78,
           'protect': 78,
           'rule': 78,
           'labor': 77,
           'every': 77,
           'inside': 77,
           'tom': 77,
           'nra': 77,
           'chair': 77,
           'left': 77,
           'teachers': 77,
           'caucus': 77,
           'long': 76,
           'reveals': 76,
           'romney': 76,
           'jr': 76,
           'brown': 76,
           'asked': 76,
           'message': 76,
           'staff': 76,
           'looks': 76,
           'once': 76,
           'interview': 75,
           'private': 75,
           'eric': 75,
           'womens': 75,
           'lose': 75,
           'children': 75,
           'crime': 75,
           'tuesdays': 75,
           'chuck': 75,
           'puerto': 74,
           'using': 74,
           'san': 74,
           'mark': 74,
           'facebook': 74,
           'allegations': 74,
           'home': 73,
           'issues': 73,
           'rips': 73,
           'giuliani': 73,
           'walker': 73,
           'wednesdays': 73,
           'needs': 73,
           'graham': 73,
           'paris': 72,
           'michigan': 72,
           'ethics': 72,
           'visit': 72,
           'hold': 72,
           'program': 71,
           'close': 71,
           'cops': 71,
           'student': 71,
           'millions': 71,
           'doing': 71,
           'resign': 71,
           'lindsey': 71,
           'economic': 71,
           'united': 70,
           'called': 70,
           'mitt': 70,
           'charlottesville': 70,
           'families': 70,
           'boehner': 70,
           'thursdays': 70,
           'question': 70,
           'address': 70,
           'arizona': 70,
           'final': 70,
           'percent': 69,
           'likely': 69,
           'won': 69,
           'something': 69,
           'past': 69,
           'challenge': 69,
           'protests': 69,
           'head': 69,
           'lost': 69,
           'nothing': 69,
           'bannon': 69,
           'men': 68,
           'biggest': 68,
           'come': 68,
           'members': 68,
           'town': 68,
           'west': 68,
           'china': 68,
           'battle': 68,
           'mean': 68,
           'jobs': 68,
           'lets': 67,
           'jared': 67,
           'paid': 67,
           'wage': 67,
           'kushner': 67,
           'fired': 67,
           'full': 67,
           'strategy': 67,
           'mondays': 67,
           'freedom': 67,
           'accused': 67,
           'issue': 67,
           'passes': 66,
           'impeachment': 66,
           'abuse': 66,
           'sue': 66,
           'well': 66,
           'schumer': 66,
           'veterans': 65,
           'sean': 65,
           'lot': 65,
           'less': 65,
           'criminal': 65,
           'reports': 65,
           'used': 65,
           'little': 65,
           'food': 65,
           'pennsylvania': 65,
           'hearing': 65,
           'pass': 64,
           'terrorism': 64,
           'comes': 64,
           'working': 64,
           'cities': 64,
           'elections': 64,
           'pac': 64,
           'orders': 64,
           'conway': 64,
           'returns': 64,
           'role': 64,
           'any': 64,
           'arrested': 63,
           'name': 63,
           'between': 63,
           'deportation': 63,
           'post': 63,
           'test': 63,
           'muslims': 63,
           'governors': 63,
           'ties': 63,
           'cnn': 62,
           'hope': 62,
           'tries': 62,
           'blames': 62,
           'taking': 62,
           'month': 62,
           'religious': 62,
           'game': 62,
           'harry': 62,
           'reid': 62,
           'lawyers': 62,
           'david': 62,
           'far': 62,
           'feds': 61,
           'id': 61,
           'afghanistan': 61,
           'data': 61,
           'fridays': 61,
           'happened': 61,
           'king': 61,
           'then': 61,
           'dangerous': 61,
           'un': 61,
           'ask': 61,
           'ruling': 61,
           'himself': 60,
           'bid': 60,
           'kellyanne': 60,
           'coronavirus': 60,
           'continues': 60,
           'through': 60,
           'michelle': 60,
           'step': 60,
           'agenda': 60,
           'politicians': 60,
           'defend': 59,
           'effort': 59,
           'possible': 59,
           'young': 59,
           'huge': 59,
           'lies': 59,
           'rudy': 59,
           'refuses': 59,
           'coming': 59,
           'wisconsin': 59,
           'company': 59,
           'chicago': 59,
           'daca': 59,
           'middle': 59,
           'kentucky': 59,
           'thousands': 59,
           'undocumented': 58,
           'everything': 58,
           'reason': 58,
           'urges': 58,
           'debt': 58,
           'torture': 58,
           'sanctions': 58,
           'fighting': 58,
           'break': 58,
           'oregon': 57,
           'believe': 57,
           'threatens': 57,
           'helped': 57,
           'enough': 57,
           'jan': 57,
           'become': 57,
           'infrastructure': 57,
           'medical': 57,
           'probably': 57,
           'son': 57,
           'book': 57,
           'cost': 57,
           'racism': 57,
           'charges': 57,
           'human': 56,
           'presidents': 56,
           'donors': 56,
           'flag': 56,

In [14]:
def unigram_prob(word, model):
    return (model["word_counts"].get(word, 0) + 1) / (
        model["total_tokens"] + model["vocab_size"]
    )

In [15]:
def unigram_log_likelihood(tokens, model):
    log_prob = 0.0
    for word in tokens:
        prob = unigram_prob(word, model)
        log_prob += math.log(prob)
    return log_prob

In [16]:
def classify_unigram(tokens, unigram_models):
    scores = {}
    for category, model in unigram_models.items():
        scores[category] = unigram_log_likelihood(tokens, model)
    
    return max(scores, key=scores.get)

In [18]:
sample_tokens = test_df.iloc[0]["tokens"]
true_label = test_df.iloc[0]["category_10"]

pred_label = classify_unigram(sample_tokens, unigram_models)

print("Tokens:", sample_tokens)
print("True label:", true_label)
print("Predicted label:", pred_label)

Tokens: ['<', 'NUM', '>', 'body', 'language', 'blunders', 'that', 'make', 'you', 'look', 'bad']
True label: OTHER
Predicted label: WELLNESS

In [20]:
y_true = test_df["category_10"].tolist()
y_pred = []

for tokens in test_df["tokens"]:
    pred = classify_unigram(tokens, unigram_models)
    y_pred.append(pred)

accuracy = accuracy_score(y_true, y_pred)
print(f"Unigram LM Accuracy: {accuracy:.4f}")

Unigram LM Accuracy: 0.4799

In [21]:
cm = confusion_matrix(y_true, y_pred, labels=categories)
cm_df = pd.DataFrame(cm, index=categories, columns=categories)
print(cm_df)
report = classification_report(y_true, y_pred, labels=categories)
print(report)

                POLITICS  OTHER  STYLE & BEAUTY  WELLNESS  TRAVEL  \
POLITICS            5081    222              41       114      93
OTHER               1595   3472             962      2412    1237
STYLE & BEAUTY         8     17            1548        82      44
WELLNESS              28     90              38      2463     138
TRAVEL                12     26              34        36    1584
ENTERTAINMENT        111     74             210        62      87
SPORTS                 9     12              11        17      16
FOOD & DRINK           1     14               8        35      50
QUEER VOICES          34     22              11        43      22
BUSINESS              67     24               8        90      49

                ENTERTAINMENT  SPORTS  FOOD & DRINK  QUEER VOICES  BUSINESS
POLITICS                  109     263            90           419       689
OTHER                    1227    1466          1633          2519      2507
STYLE & BEAUTY             30      24            93            49        68
WELLNESS                   43      91           303           144       251
TRAVEL                     11      44           110            46        77
ENTERTAINMENT            2160     207            81           326       155
SPORTS                     22     855            11            36        26
FOOD & DRINK                4      13          1103            19        21
QUEER VOICES               43      29            15          1024        26
BUSINESS                   14      34            48            44       820
                precision    recall  f1-score   support

      POLITICS       0.73      0.71      0.72      7121
         OTHER       0.87      0.18      0.30     19030
STYLE & BEAUTY       0.54      0.79      0.64      1963
      WELLNESS       0.46      0.69      0.55      3589
        TRAVEL       0.48      0.80      0.60      1980
 ENTERTAINMENT       0.59      0.62      0.61      3473
        SPORTS       0.28      0.84      0.42      1015
  FOOD & DRINK       0.32      0.87      0.46      1268
  QUEER VOICES       0.22      0.81      0.35      1269
      BUSINESS       0.18      0.68      0.28      1198

      accuracy                           0.48     41906
     macro avg       0.47      0.70      0.49     41906
  weighted avg       0.69      0.48      0.46     41906